practice_23_5/bank_management/accounts/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserLogoutView, UserUpdateView, UserPasswordUpdateView


urlpatterns = [
      path('register/', UserRegistrationView.as_view(), name = 'register'),
      path('login/', UserLoginView.as_view(), name = 'login'),
      path('logout/', UserLogoutView.as_view(), name = 'logout'),
      path('profile/', UserUpdateView.as_view(), name = 'profile'),
      path('password_update/', UserPasswordUpdateView.as_view(), name = 'password_update'),
]

practice_23_5/bank_management/bank_management/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name = 'home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

practice_23_5/bank_management/transactions/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawMoneyView, LoanRequestView, PayLoanView, LoanListView, TransactionReportView, TransferMoneyView


urlpatterns = [
      path('deposit/', DepositMoneyView.as_view(), name = 'deposit_money'),
      path('report/', TransactionReportView.as_view(), name = 'transaction_report'),
      path('withdraw/', WithdrawMoneyView.as_view(), name = 'withdraw_money'),
      path('transfer_money/', TransferMoneyView.as_view(), name = 'transfer_money'),
      path('loan_request/', LoanRequestView.as_view(), name = 'loan_request'),
      path('loans/', LoanListView.as_view(), name = 'loan_list'),
      path('loan/<int:loan_id>/', PayLoanView.as_view(), name = 'pay_loan'),
]

practice_23_5/bank_management/transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE
# Create your models here.


class Transaction(models.Model):
      account = models.ForeignKey(UserBankAccount, related_name = 'transactions', on_delete = models.CASCADE) # One user can have multiple transactions
      amount = models.DecimalField(decimal_places = 2, max_digits = 12)
      balance_after_transaction = models.DecimalField(decimal_places = 2, max_digits = 12)
      transaction_type = models.IntegerField(choices = TRANSACTION_TYPE, null = True)
      timestamp = models.DateTimeField(auto_now_add = True)
      loan_approve = models.BooleanField(default = False)
      
      
      class Meta:
            ordering = ['timestamp'] # Ordering is the built in Key word

practice_23_5/bank_management/transactions/forms.py
from django import forms
from .models import Transaction
from django.core.exceptions import ValidationError
from accounts.models import UserBankAccount

class TransactionForm(forms.ModelForm):
      class Meta:
            model = Transaction
            fields = ['amount', 'transaction_type']
            
            
      def __init__(self, *args, **kwargs):
            self.account = kwargs.pop('account') # Take account
            super().__init__(*args, **kwargs)
            self.fields['transaction_type'].disabled = True # Disable the field
            self.fields['transaction_type'].widget = forms.HiddenInput() #Hide from user
            
      def save(self, commit = True):
            # instance will call the model and find the object
            self.instance.account = self.account
            self.instance.balance_after_transaction = self.account.balance
            return super().save()
      

class DepositForm(TransactionForm):
      # For filtering amount. clean_fieldName to do validation on that field.
      def clean_amount(self):
            min_deposit_amount = 500
            amount = self.cleaned_data.get('amount') # Take amount field value
            if amount < min_deposit_amount:
                  raise forms.ValidationError(
                        f'You need to deposit at least {min_deposit_amount}'
                  )
            return amount

class WithdrawFrom(TransactionForm):
      def clean_amount(self):
            account = self.account
            min_withdraw_amount = 500
            max_withdraw_amount = 20000
            balance = account.balance
            amount = self.cleaned_data.get('amount')
            if amount < min_withdraw_amount:
                  raise forms.ValidationError(
                        f'You can withdraw at least {min_withdraw_amount}'
                  )
                  
            if amount > max_withdraw_amount:
                  raise forms.ValidationError(
                        f'You can withdraw at most {max_withdraw_amount}'
                  )
            
            if amount > balance:
                  raise forms.ValidationError(
                        f'You have {balance} in your account. '
                        'You can not withdraw more than your account balance.'
                  )
            
            return amount
      
class LoanRequestForm(TransactionForm):
      def clean_amount(self):
            amount = self.cleaned_data.get('amount')
            
            return amount

class TransferAmountForm(TransactionForm):
      recipient_account_number = forms.CharField(label = 'Recipient Account Number', max_length = 20)
      
      def clean_amount(self):
            sender_account = self.account
            min_transfer_amount = 500
            max_transfer_amount = 10000
            sender_balance = sender_account.balance
            amount = self.cleaned_data.get('amount')
            if amount < min_transfer_amount:
                  raise forms.ValidationError(
                        f'You can transfer at least {min_transfer_amount}'
                  )
                  
            if amount > max_transfer_amount:
                  raise forms.ValidationError(
                        f'You can transfer at most {max_transfer_amount}'
                  )
            
            if amount > sender_balance:
                  raise forms.ValidationError(
                        f'You have {balance} in your account. '
                        'You can not transfer more than your account balance.'
                  )
            
            return amount
      
      def clean_recipient_account(self):
            recipient_account_number = self.cleaned_data.get('recipient_account_number')
            
            if not UserBankAccount.objects.get(account_no = recipient_account_number):
                  raise forms.ValidationError(
                        f'Recipient account not found'
                  )
            else:
                  return recipient_account_number

practice_23_5/bank_management/transactions/views.py
from django.views.generic import CreateView, ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Transaction
from accounts.models import UserBankAccount
from .forms import DepositForm, WithdrawFrom, LoanRequestForm, TransferAmountForm
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID, TRANSFER_AMOUNT
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string



def send_transactions_email(user, amount, subject, template):
      # Sending auto mail to user
      message = render_to_string(template, {
                  'user': user,
                  'amount': amount,
      })
      send_email = EmailMultiAlternatives(subject, '', to = [user.email])
      send_email.attach_alternative(message, "text/html")
      send_email.send()
      # sending email finish      


# A single transaction views for make deposit, withdraw and loan
class TransactionCreateMixin(LoginRequiredMixin, CreateView):
      template_name = 'transactions/transaction_form.html'
      model = Transaction
      title = ''
      success_url = reverse_lazy('transaction_report')
      
      
      
      def get_form_kwargs(self):
            kwargs = super().get_form_kwargs()
            kwargs.update({
                  'account': self.request.user.account
            })
            return kwargs
      
      def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context.update({
                  'title': self.title,
            })
            return context
      

class DepositMoneyView(TransactionCreateMixin):
      form_class = DepositForm
      title = 'Deposit'
      
      
      def get_initial(self):
            initial = {'transaction_type': DEPOSIT}
            return initial
      
      def form_valid(self, form):
            amount = form.cleaned_data.get('amount')
            account = self.request.user.account
            account.balance += amount          # Add new balance to old balance
            account.save(
                  update_fields = ['balance']
            )
            messages.success(self.request, f'Amount {amount} was deposited to your account successfully.')
            
            # Sending auto mail to user
            send_transactions_email(self.request.user, amount, 'Deposit Balance', 'transactions/deposit_email.html')
      
            
            return super().form_valid(form)           # It inherit the class and make override
      
    
class WithdrawMoneyView(TransactionCreateMixin):
      form_class = WithdrawFrom
      title = 'Withdraw Money'
      
      
      def get_initial(self):
            initial = {'transaction_type': WITHDRAWAL}
            return initial
      
      def form_valid(self, form):
            amount = form.cleaned_data.get('amount')
            account = self.request.user.account
            
            try: 
                  # attempting to withdraw money
                  account.balance -= amount          # Subtract request balance to old balance
                  account.save(
                        update_fields = ['balance']
                  )
                  messages.success(self.request, f'Amount {amount} was withdrawal from your account successfully.')
                  
                  send_transactions_email(self.request.user, amount, 'Withdrawal Balance', 'transactions/withdrawal_email.html')
            
                  return super().form_valid(form)           # It inherit the class and make override
            except Exception:
                  messages.error(self.request, f'The bank is bankrupt.')
                  return self.form_invalid(form)
      
     
class LoanRequestView(TransactionCreateMixin):
      form_class = LoanRequestForm
      title = 'Request For Loan'
      
      
      def get_initial(self):
            initial = {'transaction_type': LOAN}
            return initial
      
      def form_valid(self, form):
            amount = form.cleaned_data.get('amount')
            current_loan_count = Transaction.objects.filter(account = self.request.user.account, transaction_type = 3, loan_approve = True).count()         # Get the transactions history and filter the result with transaction_type(LOAN) and loan approve is true
            
            if current_loan_count >= 3:
                  return HttpResponse('You have crossed your limits.')
            messages.success(self.request, f'Loan request for {amount} has sent successfully.')
            
            send_transactions_email(self.request.user, amount, 'Loan Request Message', 'transactions/loan_email.html')
            
            return super().form_valid(form)           # It inherit the class and make override
      
      
class TransactionReportView(LoginRequiredMixin, ListView):
      template_name = 'transactions/transaction_report.html'
      model = Transaction
      balance = 0
      title = 'Transaction Report'
      context_object_name = 'report_list'
      
      def get_queryset(self):
            # queryset 1 = if user does not make any filter then show all the result
            queryset = super().get_queryset().filter(
                  account = self.request.user.account
            )
            
            start_date_str = self.request.GET.get('start_date')
            end_date_str = self.request.GET.get('end_date')
            
            
            if start_date_str and end_date_str:
                  start_date = datetime.strptime(start_date_str, "%Y-%m-%d").date()        # Make the string date to datetime
                  end_date = datetime.strptime(end_date_str, "%Y-%m-%d").date()
                  
                  # queryset 2 = After filtering with start_date and end_date. __date__gte && __date__lte to filter by date
                  queryset = queryset.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date)      # gte = greater than equal, lte = less than equal
                  
                  self.balance = Transaction.objects.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date).aggregate(Sum('amount'))['amount__sum']
            else:
                  # self.balance = self.request.user.account.balance
                  self.balance = queryset.aggregate(Sum('amount'))['amount__sum']
                  
            return queryset.distinct()
      
      
      def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context.update({
                  'account': self.request.user.account,
                  'total_amount': self.balance,
            })
            return context


class PayLoanView(LoginRequiredMixin, View):
      def get(self, request, loan_id):
            loan = get_object_or_404(Transaction, id = loan_id)
            
            if loan.loan_approve: 
                  # Update user account balance
                  user_account = loan.account
                  if loan.amount < user_account.balance:
                        user_account.balance -= loan.amount
                        loan.balance_after_transaction = user_account.balance
                        user_account.save()
                        # update loan sheet
                        loan.transaction_type = LOAN_PAID
                        loan.save()
                        return redirect('loan_list')
                  else:
                        messages.error(self.request, f'Loan amount is greater than available balance.')
            return redirect('loan_list')
                  
               
class LoanListView(LoginRequiredMixin, ListView):
      model = Transaction
      template_name = 'transactions/loan_request.html'
      context_object_name = 'loans'
      
      def get_queryset(self):
            user_account = self.request.user.account
            queryset = Transaction.objects.filter(account = user_account, transaction_type = LOAN)
            return queryset
      
      
class TransferMoneyView(TransactionCreateMixin):
      form_class = TransferAmountForm
      title = 'Transfer Amount'
      
      def get_initial(self):
            initial = {'transaction_type': TRANSFER_AMOUNT}
            return initial
      
      def form_valid(self, form):
            amount = form.cleaned_data.get('amount')
            sender_account = self.request.user.account
            recipient_account_number = form.cleaned_data.get('recipient_account_number')
            recipient_account = UserBankAccount.objects.get(account_no = recipient_account_number)
            
            # Update balance for both accounts
            sender_account.balance -= amount
            recipient_account.balance += amount
                  
            sender_account.save(
                  update_fields = ['balance']
            )
            messages.success(self.request, f'Transfer amount BDT{amount} to acc_no:{recipient_account} successfully.')
            
            recipient_account.save()
            
            # send email to the sender
            sender = self.request.user
            send_transactions_email(sender, amount, 'Send Money', 'transactions/send_money_email.html')
            
            # send email to the recipient
            receiver = recipient_account.user
            send_transactions_email(receiver, amount, 'Receive Money', 'transactions/receive_money_email.html')
            
            return super().form_valid(form)
                  

practice_23_5/bank_management/transactions/templates/transactions/admin_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<h2>Congratulations! Your Loan Request has been approved</h2>
<p>after loan approval your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<h4>Our Bank</h4>

practice_23_5/bank_management/transactions/templates/transactions/deposit_email.html
<h5>Hello {{user.first_name}} {{user.last_name}}</h5>

<p>Your deposit request for BDT{{amount}} has been successfully completed. After deposit your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<h6>Our Bank</h6>

practice_23_5/bank_management/transactions/templates/transactions/loan_email.html
<h5>Hello {{user.first_name}} {{user.last_name}}</h5>

<p>Your loan request for BDT{{amount}} has been successfully send to admin. Wait for admin approval. After getting admin approval you will get a confirmation mail.</p>

<p>Thanks for banking with us.</p>
<h6>Our Bank</h6>

practice_23_5/bank_management/transactions/templates/transactions/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block body %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay_loan" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

practice_23_5/bank_management/transactions/templates/transactions/receive_money_email.html
<h2>Hello {{user.first_name}} {{user.last_name}}</h2>

<p>You get BDT{{amount}}. After receive your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<h4>Our Bank</h4>

practice_23_5/bank_management/transactions/templates/transactions/send_money_email.html
<h2>Hello {{user.first_name}} {{user.last_name}}</h2>

<p>Your transfer request for BDT{{amount}} has been successfully completed. After transfer your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<h4>Our Bank</h4>

practice_23_5/bank_management/transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %} 
{% block title %}
{{ title }}
{% endblock %} 


{% block body %}
<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Request For Loan' %}
<div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a></div>
        {% endif %}
        
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            {% if title == 'Transfer Amount' %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="recipient_account_number">
                        Recipient Account Number
                    </label>
                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="recipient_account_number" id="recipient_account_number" type="text" required placeholder="Recipient Account Number">
                </div>
                {% if form.recipient_account_number.errors %}
                    {% for error in form.recipient_account_number.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            {% endif %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                Submit
            </button>
            </div>
        </form>
    </div>
    
</div>
{% endblock %}

practice_23_5/bank_management/transactions/templates/transactions/transaction_report.html
{% extends 'base.html' %} 
<!-- Humanize helps to visualize data with more human readability -->
{% load humanize %}   
{% block head_title %}{% endblock %} {% block body %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      <!-- object_list: built in object list for ListView -->
      {% for transaction in report_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% elif transaction.get_transaction_type_display == 'Transfer Amount' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          <!-- intcomma helps to make comma after every thousands number -->
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="2">Total Transactions Amount : </th>
        <th class="px-4 py-2 text-left">
          $ {{ total_amount|default:'0'|floatformat:2|intcomma }}
        </th>
        <th class="px-4 py-2"></th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

practice_23_5/bank_management/transactions/templates/transactions/withdrawal_email.html
<h5>Hello {{user.first_name}} {{user.last_name}}</h5>

<p>Your withdrawal request for BDT{{amount}} has been successfully completed. After withdraw your total amount is {{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<h6>Our Bank</h6>